# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: simulation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'simulation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10simulation.proto\x12\nhelloworld\"\r\n\x0bTickRequest\"\x0e\n\x0cTickResponse2P\n\x11SimulationService\x12;\n\x04Tick\x12\x17.helloworld.TickRequest\x1a\x18.helloworld.TickResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'simulation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TICKREQUEST']._serialized_start=32
  _globals['_TICKREQUEST']._serialized_end=45
  _globals['_TICKRESPONSE']._serialized_start=47
  _globals['_TICKRESPONSE']._serialized_end=61
  _globals['_SIMULATIONSERVICE']._serialized_start=63
  _globals['_SIMULATIONSERVICE']._serialized_end=143
# @@protoc_insertion_point(module_scope)
